package com.siftandroidsdk.sift.tracker.models

import java.util.*


data class SiftContext(
        val timestamp: Any? = System.currentTimeMillis(),
        var event_id: UUID? = null,
        val android_idfa: String? = "",
        var account_id: String? = "Comcast",
        var partner_id: String? = "Partner ID",
        var device_id: String? = "Device ID",
        var app_ver: String? = "",
        var app_name: String? = "",
        var trace_id: String? = "",
        var sent_timestamp: String? = "",
        var device_timestamp: Long? = 0L,
        var true_timestamp: Long? = 0L,
        val device_type: String? = "",
        val device_make: String? = "",
        val device_model: String? = "",
        val device_name: String? = "",
        val device_language: String? = "",
        val device_timezone: Int = TimeZone.getDefault().rawOffset,
        val platform: String? = "",
        val os_ver: String? = "",
        val receiver_id: String? = "",
        val device_mac: String? = "",
        val session_id: String? = "",
        val subsession_uuid: String? = "",
        val subsession_type: String? = "",
        var event_name: String? = "",
        val event_type: String? = "",
        var breadcrumb: String? = "",
        var carrier: String? = "",
        val event_schema: String? = "",
        var custom_schema: String? = "",
        var network_type: String? = "",
        var screen_flow: List<String> = listOf(""),
        val bearing: Any? = 0.0f,
        val altitude: Any? = 0.0f,
        val app_build: String? = "",
        val user_id: String? = "",
        val app_version: String? = "",
        val viewport: String? = "",
        val basisForProcessing: String? = "",
        val documentId: String? = "",
        val documentVersion: String? = "",
        val documentDescription: String? = "",
        val screen_id: String? = "",
        val screen_name: String? = "",
        val screen_fragment: String? = "",
        val screen_activity: String? = "",
        val screen_type: String? = "",
        val color_depth: String? = "",
        val domain_uid: String? = "",
        val ip_address: String? = "",
        val longitude: Any? = 0.0f,
        val speed: Any? = 0.0f,
        val latitude: Any? = 0.0f,
        val network_uuid: String? = "",
        val namespace: String? = "",
        val network_technology: String? = "",
        val language: String? = "",
        val latlong_accuracy: Any? = 0.0f,
        val os_type: String? = "",
        val library_ver: String? = "",
        val session_first_id: String? = "",
        val first_event_id: String? = "",
        val session_index: Int? = -1,
        val session_previous_index: String? = "",
        val session_user_id: String? = "",
        val session_storage: String? = "",
)